//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace breadCompany.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GanjaBreadCompanyEntity : DbContext
    {
        public GanjaBreadCompanyEntity()
            : base("name=GanjaBreadCompanyEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CountForDays> CountForDays { get; set; }
        public virtual DbSet<MarketList> MarketList { get; set; }
        public virtual DbSet<Months> Months { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Subsidiary> Subsidiary { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
